name: pocket_kanye
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  google_fonts: ^1.1.0
  vibrate: ^0.0.4
  screenshot: ^0.2.0
  path_provider: ^1.6.10
  esys_flutter_share: ^1.0.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
